# Build specification
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          sudo apt-get install -y --no-install-recommends gcc g++ python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
  - job: macOS_10_13
    pool:
      vmImage: macOS-10.13
    steps:
      - script: |
          export SDKROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
          python3 -m venv venv
          source venv/bin/activate
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
  - job: macOS_10_14
    pool:
      vmImage: macOS-10.14
    steps:
      - script: |
          export SDKROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
          python3 -m venv venv
          source venv/bin/activate
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
