# Build specification
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
  - job: macOS_10_13
    pool:
      vmImage: macOS-10.13
    steps:
      - script: |
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
  - job: macOS_10_14
    pool:
      vmImage: macOS-10.14
    steps:
      - script: |
          pip install cmake ninja
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
          ninja
          ./runme
